name: bloodbank_donors
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  awesome_dialog: ^3.0.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  cloud_functions: ^6.0.4
  http: ^1.6.0
  firebase_messaging: 16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
